CREATE TABLE rezerwacje_log
(
    ID_WPISU INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    NR_REZERWACJI INT,
    DATA DATE,
    STATUS CHAR(1),

    CONSTRAINT REZERWACJE_LOG_PK PRIMARY KEY
    (
        ID_WPISU
    ) ENABLE,

    CONSTRAINT REZERWACJE_LOG_FK FOREIGN KEY
    (
        NR_REZERWACJI
    )
    REFERENCES REZERWACJE
    (
        NR_REZERWACJI
    ) ENABLE
);